language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - pytest
  - "make --directory=docs html"
  - "yapf -dr *.py docs/*.py tests/*.py tools/*.py examples/*.py gdspy/*.py"
